In [2]:
import numpy as np

import time

## vectorization

### for loop is awful

In [3]:
a=np.random.rand(100000)
b=np.random.rand(100000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("this is vectorization time",str(1000*(toc-tic))+"ms")

c=0
tic = time.time()
for i in range(100000):
    c+=a[i]*b[i]
toc = time.time()
print("this is for loop time",str(1000*(toc-tic))+"ms")

('this is vectorization time', '0.370025634766ms')
('this is for loop time', '83.4109783173ms')


### basic transition

In [4]:
v = np.random.rand(100000)
u = np.exp(v)
print u


[ 1.24948018  1.07369709  1.52154273 ...,  2.18760655  1.13167971
  1.56881184]


In [6]:
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print A[1:3,2]
cal = A.sum(axis=0)
print cal
print cal.reshape(1,4)
percentage = 100*A/(cal.reshape(1,4))
print percentage
print cal.reshape(4,1)

[ 52.  99.]
[  59.   239.   155.4   76.9]
[[  59.   239.   155.4   76.9]]
[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]
[[  59. ]
 [ 239. ]
 [ 155.4]
 [  76.9]]


## some trick

### dont use like this

In [27]:
a = np.random.randn(5)
print a

[ 0.96228462  1.00796744 -1.14907959  1.41681064 -0.12452124]


### instead use these

In [9]:
a = np.random.randn(5,1)
print a
print a[1,0]
print (a>0)

[[ 1.45947163]
 [-0.33951418]
 [-1.5970304 ]
 [-0.56317825]
 [ 1.08793311]]
-0.339514180873
[[ True]
 [False]
 [False]
 [False]
 [ True]]


In [37]:
a = np.random.randn(1,5)
assert(a.shape == (5,1))
#print a

In [36]:
a = np.random.randn(5)
a=a.reshape((1,5))
assert(a.shape==(1,5))

In [1]:
import numpy as np

In [3]:
print np.log(np.exp(2))

2.0
