In [1]:
import tensorflow as tf

In [58]:
a = tf.multinomial(tf.identity([[0.5, 0.5, 0.5]]), 5)
b = tf.random_normal((2,))
c = tf.exp(.20, name = "c")
with tf.Session() as sess:
    print(a.eval())
    print(b.eval())
    print(tf.identity([[0.5]]).eval())

[[1 0 1 0 2]]
[-2.44215369  2.60360527]
[[ 0.5]]


In [59]:
import numpy as np

In [64]:
a = np.ones_like([1,1,0, 3])
b = np.concatenate([[2,2,3]])
print(a)
print(b)

[1 1 1 1]
[2 2 3]


In [80]:
a = [3,4]
a.append(3)
print(a[None])
print(np.concatenate([[a], [a]]))


TypeError: list indices must be integers or slices, not NoneType

In [84]:
a = [2,3,4]
b = a.copy()
b = b*2
print(b)

[2, 3, 4, 2, 3, 4]


In [94]:
q = [i  for j in range(4)for i in range(j, 5)]
a = np.sum(q)
print(a)

36


In [95]:
a = [[2,3,4]]
#a = np.array(a)
len(np.concatenate(a))


3